# Generated by Django 4.1.4 on 2022-12-16 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('private_access', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('catalog', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='incommonpanel.catalog')),
            ],
        ),
    ]
